---
on examine: dialog
dialog:
  initial dialog:
  - id: ask whats up
    text: hey guy, what's up?
    audio: audio file
    responses:
    - text: nothing much
      audio: audio file
      next dialog: gets bored
    - text: a whole lot
      audio: audio file
      next dialog: gets excited
  - id: gets bored
    text: well that's boring.  You bore me, go away
    audio: audio file
  - id: gets excited
    text: Wow, sounds exciting. I'm gonna do a thing and also say different stuff next time
    audio: audio file
    actions:
      set dialog: gave item
      give item: some item or something
  gave item:
  - id: gave item
    text: how's that item treatin' you? .... I have nothing else to say.  Go away.
    audio: audio file
  gets shot:
  - id: initial outburst
    text: wtf mark? why would you do that
    audio: audio file
    responses:
    - text: because I'm a ponce
      audio: audio file
      next dialog: gets pissed at being shot
    - text: because you killed mike
      audio: audio file
      next dialog: deny accusation
  - id: deny accusation
    text: that's not true
    audio: audio file
    responses:
    - text: uhoh, could it have been someone else
      audio: audio file
      next dialog: gets pissed at being shot
  - id: gets pissed at being shot
    text: you idiot, now I'm gonna die.  buhhhhhh I'm dead
    audio: audio file
    set dialog: post shooting
on click:
  - move to and examine: true
on use item:
  gun:
    set dialog: been shot
    do dialog: true
  default:
    show dialog: I guess I can't use that here.
player move to position:
- 10
- 0
player move to image: idle.png